instrument:
  instrument_name: euclid
  survey_name: deep
  grism_type: red
  data_release: DR1
  quality:
    pixel_mask:
    - 0
    n_min_dithers: 16
instrument_constants:
  wavelengths_blue:
  - 9260.0
  - 13660.0
  wavelengths_red:
  - 11900.0
  - 19002.0
  R: 600
  reference_lambda: 16000
  units: erg/s/cm2/A
  units_scale_factor: 1.0e-16
io:
  spectra_mode: metadata path
  input_dir: inputs/OPT_UV_DESI_z01_075
  filename_in: OPT_UV_DESI_NII_SF
  filename_in_extention: csv
  output_dir: stacked_spectra/OPT_UV_DESI_z01_075
  spectra_datafile: metadata
  filename_out: AUTO
cosmology:
  cosmo_H0: 70.0
  cosmo_Om0: 0.3
redshift:
  z_type: rest_frame
norm:
  spectra_normalization: interval
  lambda_norm_min: 10000.0
  lambda_norm_max: 10600.0
  interval_norm_statistics: median
catalog_columns:
  ID_column_name: source_id
  redshift_column_name: Z
  metadata:
    metadata_path_column_name: datalabs_path
    metadata_file_column_name: file_name
    metadata_indx_column_name: hdu_index
  galactic_extinction_parameters:
    galactic_extinction: true
    gal_ext_column_name: gal_ebv
resampling:
  pixel_resampling_type: lambda
  pixel_size_type: manual
  pixel_resampling: 4.0
spectrum_edges:
- 10
- -10
bootstrap:
  bootstrapping_R: 1
sigmaclip:
  sigma_clipping_conditions: 3.0
parallel:
  multiprocessing: true
  max_cpu_fraction: 1.0
plot:
  plot_results: true
config_version: 1.0.0
